# Generated by Django 5.2.8 on 2025-11-07 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField()),
                ('task_type', models.CharField(choices=[('create_content', 'Create Content'), ('create_code', 'Create Code'), ('research', 'Research'), ('deep_research', 'Deep Research / Analysis'), ('plan_organize', 'Plan & Organize'), ('ideate', 'Ideate / Brainstorm'), ('summarize', 'Summarize / Review'), ('explain', 'Explain / Teach'), ('optimize', 'Optimize / Improve')], max_length=50)),
                ('output_format', models.CharField(choices=[('text', 'Text'), ('code', 'Code'), ('chart_graph', 'Chart / Graph'), ('checklist_table', 'Checklist / Table'), ('template_framework', 'Template / Framework'), ('image_visual', 'Image / Visual'), ('slide_report', 'Slide / Report')], max_length=50)),
                ('category', models.CharField(choices=[('marketing', 'Marketing'), ('sales', 'Sales'), ('engineering', 'Engineering'), ('design', 'Design'), ('product_management', 'Product Management'), ('hr', 'Human Resources (HR)'), ('finance', 'Finance'), ('support', 'Customer Support'), ('content_comms', 'Content & Communications'), ('learning', 'Learning & Development')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
