# Generated by Django 5.2.8 on 2025-11-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
