# Generated by Django 5.2.8 on 2025-11-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_prompt_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='guidance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='prompt_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
