# Generated by Django 5.2.8 on 2025-11-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_prompt_guidance_prompt_prompt_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
