# Generated by Django 5.2.8 on 2025-11-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_prompt_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='prompt',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
