# Generated by Django 5.2.8 on 2025-11-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_prompt_status_prompt_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
    ]
