# Generated by Django 5.2.8 on 2025-11-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='dislike_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prompt',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'Upvote'), (1, 'Downvote')]),
        ),
    ]
