# Generated by Django 5.2.8 on 2025-11-17 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_bookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('prompt_description', models.TextField(blank=True, null=True)),
                ('prompt_text', models.TextField()),
                ('guidance', models.TextField(blank=True, null=True)),
                ('task_type', models.CharField(choices=[('create_content', 'Create Content'), ('create_code', 'Create Code'), ('research', 'Research'), ('deep_research', 'Deep Research / Analysis'), ('plan_organize', 'Plan & Organize'), ('ideate', 'Ideate / Brainstorm'), ('summarize', 'Summarize / Review'), ('explain', 'Explain / Teach'), ('optimize', 'Optimize / Improve')], max_length=50)),
                ('output_format', models.CharField(choices=[('text', 'Text'), ('code', 'Code'), ('chart_graph', 'Chart / Graph'), ('checklist_table', 'Checklist / Table'), ('template_framework', 'Template / Framework'), ('image_visual', 'Image / Visual'), ('slide_report', 'Slide / Report')], max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.prompt')),
            ],
            options={
                'ordering': ['-version_created_at'],
            },
        ),
    ]
