# Generated by Django 5.2.8 on 2025-11-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_promptversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pending_deletion', 'Pending Deletion')], db_index=True, default='pending', max_length=20),
        ),
    ]
