# Generated by Django 5.2.8 on 2025-11-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_prompt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')]),
        ),
    ]
